name: Build TXT Viewer
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  ufbt-build-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build with ufbt
        uses: flipperdevices/flipperzero-ufbt-action@v0.1
        id: build-app
        with:
          sdk-channel: dev
      - name: Upload app artifacts
        uses: actions/upload-artifact@v4
        with:
          name: txt-viewer-${{ steps.build-app.outputs.suffix }}
          path: ${{ steps.build-app.outputs.fap-artifacts }}
