name: Build TXT Viewer
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install uFBT
        run: |
          python -m pip install --upgrade pip
          python -m pip install ufbt
      - name: Initialize ufbt
        run: ufbt init
      - name: Build app
        run: ufbt build
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: txt-viewer
          path: build/**
